FROM golang:1.27.1-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o server ./cmd/server/main.go

FROM gcr.io/distroless/static-debian13
WORKDIR /app
COPY --from=builder /app/server .
ENTRYPOINT ["./server"]
