FROM golang:1.27.1-alpine3.24 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -o worker ./cmd/worker/main.go

FROM gcr.io/distroless/static-debian13:nonroot
WORKDIR /app
COPY --from=builder /app/worker .
ENTRYPOINT ["/app/worker"]
