// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"
	"uuid"

	mock "github.com/stretchr/testify/mock"
	"github.com/sudeeya/gophprofile/internal/broker"
	"github.com/sudeeya/gophprofile/internal/repository"
	"github.com/sudeeya/gophprofile/internal/storage"
)

// NewMockAvatarRepository creates a new instance of MockAvatarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAvatarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAvatarRepository is an autogenerated mock type for the AvatarRepository type
type MockAvatarRepository struct {
	mock.Mock
}

type MockAvatarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarRepository) EXPECT() *MockAvatarRepository_Expecter {
	return &MockAvatarRepository_Expecter{mock: &_m.Mock}
}

// AddThumbnailKey provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) AddThumbnailKey(ctx context.Context, input repository.AddThumbnailKeyInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddThumbnailKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.AddThumbnailKeyInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarRepository_AddThumbnailKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddThumbnailKey'
type MockAvatarRepository_AddThumbnailKey_Call struct {
	*mock.Call
}

// AddThumbnailKey is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.AddThumbnailKeyInput
func (_e *MockAvatarRepository_Expecter) AddThumbnailKey(ctx any, input any) *MockAvatarRepository_AddThumbnailKey_Call {
	return &MockAvatarRepository_AddThumbnailKey_Call{Call: _e.mock.On("AddThumbnailKey", ctx, input)}
}

func (_c *MockAvatarRepository_AddThumbnailKey_Call) Run(run func(ctx context.Context, input repository.AddThumbnailKeyInput)) *MockAvatarRepository_AddThumbnailKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.AddThumbnailKeyInput
		if args[1] != nil {
			arg1 = args[1].(repository.AddThumbnailKeyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_AddThumbnailKey_Call) Return(err error) *MockAvatarRepository_AddThumbnailKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarRepository_AddThumbnailKey_Call) RunAndReturn(run func(ctx context.Context, input repository.AddThumbnailKeyInput) error) *MockAvatarRepository_AddThumbnailKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAvatar provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) CreateAvatar(ctx context.Context, input repository.CreateAvatarInput) (repository.CreateAvatarOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateAvatar")
	}

	var r0 repository.CreateAvatarOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateAvatarInput) (repository.CreateAvatarOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateAvatarInput) repository.CreateAvatarOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(repository.CreateAvatarOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateAvatarInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_CreateAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAvatar'
type MockAvatarRepository_CreateAvatar_Call struct {
	*mock.Call
}

// CreateAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.CreateAvatarInput
func (_e *MockAvatarRepository_Expecter) CreateAvatar(ctx any, input any) *MockAvatarRepository_CreateAvatar_Call {
	return &MockAvatarRepository_CreateAvatar_Call{Call: _e.mock.On("CreateAvatar", ctx, input)}
}

func (_c *MockAvatarRepository_CreateAvatar_Call) Run(run func(ctx context.Context, input repository.CreateAvatarInput)) *MockAvatarRepository_CreateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateAvatarInput
		if args[1] != nil {
			arg1 = args[1].(repository.CreateAvatarInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_CreateAvatar_Call) Return(createAvatarOutput repository.CreateAvatarOutput, err error) *MockAvatarRepository_CreateAvatar_Call {
	_c.Call.Return(createAvatarOutput, err)
	return _c
}

func (_c *MockAvatarRepository_CreateAvatar_Call) RunAndReturn(run func(ctx context.Context, input repository.CreateAvatarInput) (repository.CreateAvatarOutput, error)) *MockAvatarRepository_CreateAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAvatar provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) DeleteAvatar(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarRepository_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type MockAvatarRepository_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) DeleteAvatar(ctx any, id any) *MockAvatarRepository_DeleteAvatar_Call {
	return &MockAvatarRepository_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, id)}
}

func (_c *MockAvatarRepository_DeleteAvatar_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_DeleteAvatar_Call) Return(err error) *MockAvatarRepository_DeleteAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarRepository_DeleteAvatar_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAvatarRepository_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetAvatar(ctx context.Context, id uuid.UUID) (repository.GetAvatarOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 repository.GetAvatarOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.GetAvatarOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.GetAvatarOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.GetAvatarOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type MockAvatarRepository_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) GetAvatar(ctx any, id any) *MockAvatarRepository_GetAvatar_Call {
	return &MockAvatarRepository_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx, id)}
}

func (_c *MockAvatarRepository_GetAvatar_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetAvatar_Call) Return(getAvatarOutput repository.GetAvatarOutput, err error) *MockAvatarRepository_GetAvatar_Call {
	_c.Call.Return(getAvatarOutput, err)
	return _c
}

func (_c *MockAvatarRepository_GetAvatar_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repository.GetAvatarOutput, error)) *MockAvatarRepository_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarMetadata provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetAvatarMetadata(ctx context.Context, id uuid.UUID) (repository.GetAvatarMetadataOutput, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarMetadata")
	}

	var r0 repository.GetAvatarMetadataOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.GetAvatarMetadataOutput, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.GetAvatarMetadataOutput); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.GetAvatarMetadataOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetAvatarMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarMetadata'
type MockAvatarRepository_GetAvatarMetadata_Call struct {
	*mock.Call
}

// GetAvatarMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) GetAvatarMetadata(ctx any, id any) *MockAvatarRepository_GetAvatarMetadata_Call {
	return &MockAvatarRepository_GetAvatarMetadata_Call{Call: _e.mock.On("GetAvatarMetadata", ctx, id)}
}

func (_c *MockAvatarRepository_GetAvatarMetadata_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_GetAvatarMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetAvatarMetadata_Call) Return(getAvatarMetadataOutput repository.GetAvatarMetadataOutput, err error) *MockAvatarRepository_GetAvatarMetadata_Call {
	_c.Call.Return(getAvatarMetadataOutput, err)
	return _c
}

func (_c *MockAvatarRepository_GetAvatarMetadata_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (repository.GetAvatarMetadataOutput, error)) *MockAvatarRepository_GetAvatarMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAvatarStorage creates a new instance of MockAvatarStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarStorage {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAvatarStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAvatarStorage is an autogenerated mock type for the AvatarStorage type
type MockAvatarStorage struct {
	mock.Mock
}

type MockAvatarStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarStorage) EXPECT() *MockAvatarStorage_Expecter {
	return &MockAvatarStorage_Expecter{mock: &_m.Mock}
}

// DeleteAvatar provides a mock function for the type MockAvatarStorage
func (_mock *MockAvatarStorage) DeleteAvatar(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarStorage_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type MockAvatarStorage_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAvatarStorage_Expecter) DeleteAvatar(ctx any, key any) *MockAvatarStorage_DeleteAvatar_Call {
	return &MockAvatarStorage_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, key)}
}

func (_c *MockAvatarStorage_DeleteAvatar_Call) Run(run func(ctx context.Context, key string)) *MockAvatarStorage_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarStorage_DeleteAvatar_Call) Return(err error) *MockAvatarStorage_DeleteAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarStorage_DeleteAvatar_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockAvatarStorage_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function for the type MockAvatarStorage
func (_mock *MockAvatarStorage) GetAvatar(ctx context.Context, key string) (storage.GetAvatarOutput, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 storage.GetAvatarOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (storage.GetAvatarOutput, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) storage.GetAvatarOutput); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.GetAvatarOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarStorage_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type MockAvatarStorage_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAvatarStorage_Expecter) GetAvatar(ctx any, key any) *MockAvatarStorage_GetAvatar_Call {
	return &MockAvatarStorage_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx, key)}
}

func (_c *MockAvatarStorage_GetAvatar_Call) Run(run func(ctx context.Context, key string)) *MockAvatarStorage_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarStorage_GetAvatar_Call) Return(getAvatarOutput storage.GetAvatarOutput, err error) *MockAvatarStorage_GetAvatar_Call {
	_c.Call.Return(getAvatarOutput, err)
	return _c
}

func (_c *MockAvatarStorage_GetAvatar_Call) RunAndReturn(run func(ctx context.Context, key string) (storage.GetAvatarOutput, error)) *MockAvatarStorage_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// PutAvatar provides a mock function for the type MockAvatarStorage
func (_mock *MockAvatarStorage) PutAvatar(ctx context.Context, input storage.PutAvatarInput) (storage.PutAvatarOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutAvatar")
	}

	var r0 storage.PutAvatarOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PutAvatarInput) (storage.PutAvatarOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PutAvatarInput) storage.PutAvatarOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(storage.PutAvatarOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.PutAvatarInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarStorage_PutAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutAvatar'
type MockAvatarStorage_PutAvatar_Call struct {
	*mock.Call
}

// PutAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - input storage.PutAvatarInput
func (_e *MockAvatarStorage_Expecter) PutAvatar(ctx any, input any) *MockAvatarStorage_PutAvatar_Call {
	return &MockAvatarStorage_PutAvatar_Call{Call: _e.mock.On("PutAvatar", ctx, input)}
}

func (_c *MockAvatarStorage_PutAvatar_Call) Run(run func(ctx context.Context, input storage.PutAvatarInput)) *MockAvatarStorage_PutAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.PutAvatarInput
		if args[1] != nil {
			arg1 = args[1].(storage.PutAvatarInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarStorage_PutAvatar_Call) Return(putAvatarOutput storage.PutAvatarOutput, err error) *MockAvatarStorage_PutAvatar_Call {
	_c.Call.Return(putAvatarOutput, err)
	return _c
}

func (_c *MockAvatarStorage_PutAvatar_Call) RunAndReturn(run func(ctx context.Context, input storage.PutAvatarInput) (storage.PutAvatarOutput, error)) *MockAvatarStorage_PutAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAvatarEventPublisher creates a new instance of MockAvatarEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarEventPublisher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAvatarEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAvatarEventPublisher is an autogenerated mock type for the AvatarEventPublisher type
type MockAvatarEventPublisher struct {
	mock.Mock
}

type MockAvatarEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarEventPublisher) EXPECT() *MockAvatarEventPublisher_Expecter {
	return &MockAvatarEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishAvatarDeleteEvent provides a mock function for the type MockAvatarEventPublisher
func (_mock *MockAvatarEventPublisher) PublishAvatarDeleteEvent(ctx context.Context, event broker.AvatarDeleteEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishAvatarDeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.AvatarDeleteEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAvatarDeleteEvent'
type MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call struct {
	*mock.Call
}

// PublishAvatarDeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event broker.AvatarDeleteEvent
func (_e *MockAvatarEventPublisher_Expecter) PublishAvatarDeleteEvent(ctx any, event any) *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call {
	return &MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call{Call: _e.mock.On("PublishAvatarDeleteEvent", ctx, event)}
}

func (_c *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call) Run(run func(ctx context.Context, event broker.AvatarDeleteEvent)) *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.AvatarDeleteEvent
		if args[1] != nil {
			arg1 = args[1].(broker.AvatarDeleteEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call) Return(err error) *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call) RunAndReturn(run func(ctx context.Context, event broker.AvatarDeleteEvent) error) *MockAvatarEventPublisher_PublishAvatarDeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAvatarUploadEvent provides a mock function for the type MockAvatarEventPublisher
func (_mock *MockAvatarEventPublisher) PublishAvatarUploadEvent(ctx context.Context, event broker.AvatarUploadEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishAvatarUploadEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.AvatarUploadEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarEventPublisher_PublishAvatarUploadEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAvatarUploadEvent'
type MockAvatarEventPublisher_PublishAvatarUploadEvent_Call struct {
	*mock.Call
}

// PublishAvatarUploadEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event broker.AvatarUploadEvent
func (_e *MockAvatarEventPublisher_Expecter) PublishAvatarUploadEvent(ctx any, event any) *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call {
	return &MockAvatarEventPublisher_PublishAvatarUploadEvent_Call{Call: _e.mock.On("PublishAvatarUploadEvent", ctx, event)}
}

func (_c *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call) Run(run func(ctx context.Context, event broker.AvatarUploadEvent)) *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.AvatarUploadEvent
		if args[1] != nil {
			arg1 = args[1].(broker.AvatarUploadEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call) Return(err error) *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call) RunAndReturn(run func(ctx context.Context, event broker.AvatarUploadEvent) error) *MockAvatarEventPublisher_PublishAvatarUploadEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockPinger
func (_mock *MockPinger) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPinger_Expecter) Ping(ctx any) *MockPinger_Ping_Call {
	return &MockPinger_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPinger_Ping_Call) Run(run func(ctx context.Context)) *MockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPinger_Ping_Call) Return(err error) *MockPinger_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinger_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}
