// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"
	"uuid"

	mock "github.com/stretchr/testify/mock"
	"github.com/sudeeya/gophprofile/internal/domain"
	"github.com/sudeeya/gophprofile/internal/services"
)

// NewMockAvatarService creates a new instance of MockAvatarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAvatarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAvatarService is an autogenerated mock type for the AvatarService type
type MockAvatarService struct {
	mock.Mock
}

type MockAvatarService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarService) EXPECT() *MockAvatarService_Expecter {
	return &MockAvatarService_Expecter{mock: &_m.Mock}
}

// DeleteAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) DeleteAvatar(ctx context.Context, input services.DeleteAvatarInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.DeleteAvatarInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarService_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type MockAvatarService_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - input services.DeleteAvatarInput
func (_e *MockAvatarService_Expecter) DeleteAvatar(ctx any, input any) *MockAvatarService_DeleteAvatar_Call {
	return &MockAvatarService_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, input)}
}

func (_c *MockAvatarService_DeleteAvatar_Call) Run(run func(ctx context.Context, input services.DeleteAvatarInput)) *MockAvatarService_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.DeleteAvatarInput
		if args[1] != nil {
			arg1 = args[1].(services.DeleteAvatarInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_DeleteAvatar_Call) Return(err error) *MockAvatarService_DeleteAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarService_DeleteAvatar_Call) RunAndReturn(run func(ctx context.Context, input services.DeleteAvatarInput) error) *MockAvatarService_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) GetAvatar(ctx context.Context, id uuid.UUID) (domain.Avatar, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Avatar, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Avatar); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Avatar)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type MockAvatarService_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarService_Expecter) GetAvatar(ctx any, id any) *MockAvatarService_GetAvatar_Call {
	return &MockAvatarService_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx, id)}
}

func (_c *MockAvatarService_GetAvatar_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarService_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_GetAvatar_Call) Return(avatar domain.Avatar, err error) *MockAvatarService_GetAvatar_Call {
	_c.Call.Return(avatar, err)
	return _c
}

func (_c *MockAvatarService_GetAvatar_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Avatar, error)) *MockAvatarService_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatarMetadata provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) GetAvatarMetadata(ctx context.Context, id uuid.UUID) (domain.Metadata, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarMetadata")
	}

	var r0 domain.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Metadata, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Metadata); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_GetAvatarMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatarMetadata'
type MockAvatarService_GetAvatarMetadata_Call struct {
	*mock.Call
}

// GetAvatarMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarService_Expecter) GetAvatarMetadata(ctx any, id any) *MockAvatarService_GetAvatarMetadata_Call {
	return &MockAvatarService_GetAvatarMetadata_Call{Call: _e.mock.On("GetAvatarMetadata", ctx, id)}
}

func (_c *MockAvatarService_GetAvatarMetadata_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarService_GetAvatarMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_GetAvatarMetadata_Call) Return(metadata domain.Metadata, err error) *MockAvatarService_GetAvatarMetadata_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockAvatarService_GetAvatarMetadata_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Metadata, error)) *MockAvatarService_GetAvatarMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function for the type MockAvatarService
func (_mock *MockAvatarService) UploadAvatar(ctx context.Context, input services.UploadAvatarInput) (domain.Avatar, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.UploadAvatarInput) (domain.Avatar, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.UploadAvatarInput) domain.Avatar); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.Avatar)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.UploadAvatarInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarService_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type MockAvatarService_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - input services.UploadAvatarInput
func (_e *MockAvatarService_Expecter) UploadAvatar(ctx any, input any) *MockAvatarService_UploadAvatar_Call {
	return &MockAvatarService_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, input)}
}

func (_c *MockAvatarService_UploadAvatar_Call) Run(run func(ctx context.Context, input services.UploadAvatarInput)) *MockAvatarService_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.UploadAvatarInput
		if args[1] != nil {
			arg1 = args[1].(services.UploadAvatarInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarService_UploadAvatar_Call) Return(avatar domain.Avatar, err error) *MockAvatarService_UploadAvatar_Call {
	_c.Call.Return(avatar, err)
	return _c
}

func (_c *MockAvatarService_UploadAvatar_Call) RunAndReturn(run func(ctx context.Context, input services.UploadAvatarInput) (domain.Avatar, error)) *MockAvatarService_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthService creates a new instance of MockHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHealthService is an autogenerated mock type for the HealthService type
type MockHealthService struct {
	mock.Mock
}

type MockHealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthService) EXPECT() *MockHealthService_Expecter {
	return &MockHealthService_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockHealthService
func (_mock *MockHealthService) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockHealthService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthService_Expecter) Ping(ctx any) *MockHealthService_Ping_Call {
	return &MockHealthService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockHealthService_Ping_Call) Run(run func(ctx context.Context)) *MockHealthService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthService_Ping_Call) Return(err error) *MockHealthService_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthService_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockHealthService_Ping_Call {
	_c.Call.Return(run)
	return _c
}
